[mypy]
# List of folders to ignore entirely
exclude = (?x)(matrix_env|venv|\.venv|__pycache__|\.mypy_cache)

# MANDATORY MODULE REQUIREMENT: Strict typing
disallow_untyped_defs = True
disallow_incomplete_defs = True

# Ignore “missing imports” from external libraries
ignore_missing_imports = True